### ISSUE TITLE
3. image gallery previous next buttons

### ISSUE THREAD

**Issue by Anichki** [lashatsatsashvili/project#4]
butten-ები, სტილისტურად, როგორც გირჩევნია ან ზემოდან გალერეაზე მარჯვენა და მარცხენა მხარეს გადაადე (დაგჭირდება, position: relative და absolute) 
https://www.youtube.com/watch?v=ngt-qQKaTpA
ან დაბლა თუ გირჩევნია ვიზუალურად დაბლა მარჯვნივ და მარცხნივ განალაგე. svg-ები ცადე აგიტვირთე _supprot ფოლდერშია.

როგორც image შემოგაქვს ზუსტად ისე შეგიძლია შემოიტანო.

**Comment by lashatsatsashvili** [comment]
ase unda gameketebina ?

**Comment by lashatsatsashvili** [comment]
@Anichki  ase unda gameketebina ?

**Comment by Anichki** [comment]
ხო ვიზუალურად, როგორც მოგეწონებოდა ადგილმდებარეობა, მინდოდა მენახებინა რამდენად მარტივად შეიძლება svg-ს გამოყენება.

**Comment by lashatsatsashvili** [comment]
@Anichki ki momewona da uketesitsaa mgoni da zogadad saits ar tvirtavs ?
