### ISSUE TITLE
@font-face

### ISSUE THREAD

**Issue by Anichki** [lashatsatsashvili/project#5]
custom font (ქართულენოვანი ვებგვერდის შემთხვევაში ყოველმიზეზ გარეშე დაგჭირდება ასეთი რაღაცის გაკეთება)
ეს გამოიყენე და იკონების პრინციპსაც უფრო უკეთ მიხვდები. font-ების ფოლდერში დავამატე დაგენერირებული ფონტი.

ისე შენც შეგიძლია მაგალითად აქ დააგენერირო: https://www.web-font-generator.com/

სხვადასხვა ბროუზერსა თუ მოწყობილობას სხვადასხვა გაფართოების ფონტები სჭირდება.

გამოიყენე ეს დაგენერირებული ფონტები, თუ სურვილი გაგიჩნდება შეგიძლია სხვა დააგენერირო და გამოიყენო.
https://developer.mozilla.org/en/docs/Web/CSS/@font-face
https://css-tricks.com/snippets/css/using-font-face/

სამწუხაროდ არ არის, მაგრამ ესეც ყველა ბროუზერზე იმუშავებს: 
...('webfont.woff2') format('woff2'), /* Super Modern Browsers */

**Comment by lashatsatsashvili** [comment]
@Anichki tu sworad gavige ase unda gameketebina xo?

**Comment by Anichki** [comment]
დაახლოებით, ჩემ კომპში ეს ფონტი არ წამოიღო, უნდა გადაამოწმო სწორად თუ გაქვს ფონტისთვის sourc გაწერილი, ანუ სად უნდა იპოვნოს.

**Comment by lashatsatsashvili** [comment]
@Anichki  font-family: "HelveticaNeueL";  es sworia ? ubralod amashi shemepara tavidanve echvi
tu sxvanairad qvia ?
